# Tensor Operations

In [ ]:
import torch

In [ ]:
# Tensor = Menory + shape + stride
# Most operations like view(), transpose(), permute(), squeeze(), unsqueeze() and expand() only change SHAPE and STRIDE not memory

In [ ]:
# ============================================================
# 1. SHAPE, RANK, DTYPE, DEVICE
# ============================================================
x = torch.randn(3, 4, 5)
print("Shape:", x.shape)
print("Rank :", x.ndim)
print("Dtype:", x.dtype)
print("Device:", x.device)
# Total elements
print("Elements:", x.numel())

Shape: torch.Size([3, 4, 5])
Rank : 3
Dtype: torch.float32
Device: cpu
Elements: 60


In [ ]:
# ============================================================
# 2. STRIDES
# ============================================================
x = torch.arange(60).view(3,4,5)
print(x)
print("Shape:", x.shape)
print("Strides:", x.stride())
y = x.reshape(2, 6, 5)
print(y)
print("Shape:", y.shape)
print("Strides:", y.stride())

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
Shape: torch.Size([3, 4, 5])
Strides: (20, 5, 1)
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
Shape: torch.Size([2, 6, 5])
Strides: (30, 5, 1)


In [ ]:
# ============================================================
# 3. CONTIGUOUS TENSORS - If I walk through the tensor logically, do I also walk through memory sequentially?
# ============================================================
x = torch.arange(60).view(3,4,5)
print(x)
print("CONTIGUOUS TENSORS?:", x.is_contiguous())
y = x.transpose(0,2)
print(y)
print("CONTIGUOUS TENSORS?:", y.is_contiguous())

tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
CONTIGUOUS TENSORS?: True
tensor([[[ 0, 20, 40],
         [ 5, 25, 45],
         [10, 30, 50],
         [15, 35, 55]],

        [[ 1, 21, 41],
         [ 6, 26, 46],
         [11, 31, 51],
         [16, 36, 56]],

        [[ 2, 22, 42],
         [ 7, 27, 47],
         [12, 32, 52],
         [17, 37, 57]],

        [[ 3, 23, 43],
         [ 8, 28, 48],
         [13, 33, 53],
         [18, 38, 58]],

        [[ 4, 24, 44],
         [ 9, 29, 49],
         [14, 34, 54],
         [19, 39, 59]]])
CONTIGUOUS TENSORS?: False


In [ ]:
# ============================================================
# 4. VIEWS SHARE MEMORY
# ============================================================
x = torch.arange(60)
print(x)
y = x.view(3,4,5)
print(y)
y[0,0,0] = 99
print(x)
# x changes because:
# x and y point to same memory

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59])
tensor([[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]],

        [[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]],

        [[40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49],
         [50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59]]])
tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59])


In [ ]:
# ============================================================
# 5. CLONE
# ============================================================
x = torch.arange(12)
print(x)
y = x.clone()
y[0] = 99
print(x)

# clone() creates new memory

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [ ]:
# ============================================================
# 6. RESHAPE - It may create new memory but is contiguous
# ============================================================
x = torch.arange(60)
y = x.reshape(2,6,5)
print(y.shape)
print(y.is_contiguous())


torch.Size([2, 6, 5])
True


In [ ]:
# ============================================================
# 7. TRANSPOSE - Makes the tensor non contagiuous
# ============================================================
x = torch.arange(12).view(3,4)
print(x.shape)
y = x.transpose(0,1)
print(y.shape)
print(y.is_contiguous())
y[0,0] = 99
print(x)
y = y.contiguous()
print(y.is_contiguous())
y[0,0] = 0
print(x)

torch.Size([3, 4])
torch.Size([4, 3])
False
tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
True
tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [ ]:
# ============================================================
# 8. VIEW ERROR -  View() only works
# ============================================================
x = torch.arange(60).reshape(3, 4, 5)
y = x.transpose(0,2)
try:
    z = y.view(60)
except Exception as e:
  print(e)
# Fix:
z = y.contiguous().view(60)
print(z)

view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
tensor([ 0, 20, 40,  5, 25, 45, 10, 30, 50, 15, 35, 55,  1, 21, 41,  6, 26, 46,
        11, 31, 51, 16, 36, 56,  2, 22, 42,  7, 27, 47, 12, 32, 52, 17, 37, 57,
         3, 23, 43,  8, 28, 48, 13, 33, 53, 18, 38, 58,  4, 24, 44,  9, 29, 49,
        14, 34, 54, 19, 39, 59])


In [ ]:
# ============================================================
# 9. PERMUTE
# ============================================================
x = torch.randn(2,3,4,5)
print(x.shape)
y = x.permute(2,0,3,1)
print(y.shape)

torch.Size([2, 3, 4, 5])
torch.Size([4, 2, 5, 3])


In [ ]:
# ============================================================
# 10. UNSQUEEZE
# ============================================================
x = torch.arange(12)
print(x)
print(x.shape)
y = x.unsqueeze(0)
print(y.shape)
print(y)
y = x.unsqueeze(1)
print(y.shape)
print(y)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
torch.Size([1, 12])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
torch.Size([12, 1])
tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]])


In [ ]:
# ============================================================
# 11. SQUEEZE
# ============================================================
x = torch.randn(1,3,1,4,1)
print(x.shape)
y = x.squeeze()
print(y.shape)

torch.Size([1, 3, 1, 4, 1])
torch.Size([3, 4])


In [ ]:
# ============================================================
# 12. BROADCASTING
# ============================================================
A = torch.randn(3,4)
B = torch.randn(4)
C = A + B
print(C.shape)

A = torch.randn(2,4,5)
B = torch.randn(1,4,1)
C = A + B
print(C.shape)


torch.Size([3, 4])
torch.Size([2, 4, 5])


In [ ]:
# ============================================================
# 13. EXPAND
# ============================================================
x = torch.tensor([[1,2,3]])
print(x.shape)
y = x.expand(5,3)
print(y.shape)

# No new memory
# Uses broadcasting tricks



torch.Size([1, 3])
torch.Size([5, 3])


In [ ]:
# ============================================================
# 14. REPEAT
# ============================================================

x = torch.tensor([[1,2,3]])
y = x.repeat(5,2)
print(y.shape)
# New memory allocated
print(y)

torch.Size([5, 6])
tensor([[1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3]])


In [ ]:
# ============================================================
# 15. MATRIX MULTIPLICATIONS
# ============================================================
A = torch.randn(2, 3, 4)
B = torch.randn(4, 5)
C = A@B
print(C.shape)
x = torch.randn(2, 4, 5)
D = torch.matmul(A,x)
print(D.shape)


torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [ ]:
# ============================================================
# 16. SOFTMAX
# ============================================================
x = torch.randn(3,4)
print(x)
y = torch.softmax(x, dim=1)
print(y)


tensor([[ 0.6880, -0.7336, -1.8286,  0.5728],
        [ 0.9021,  2.4421, -1.4244, -0.1464],
        [-0.5530,  0.7967, -0.6137, -1.2980]])
tensor([[0.4518, 0.1090, 0.0365, 0.4027],
        [0.1636, 0.7631, 0.0160, 0.0573],
        [0.1594, 0.6148, 0.1500, 0.0757]])


# Excercise

In [ ]:
import torch

# ============================================================
# 1. MATRIX MULTIPLICATION - using for loops
# ============================================================
A = torch.randn(2, 3, 4)
B = torch.randn(4, 5)
def matrixmul(A: torch.Tensor, B: torch.Tensor) -> torch.Tensor:
    T_shape = list(A.shape)
    T_shape[-1] = B.shape[-1]
    T = torch.zeros(T_shape)
    if A.shape[-1] != B.shape[-2]:
        raise ValueError("A.shape[-1] != B.shape[-2]")
    else:
      if len(A.shape) == 2:
        for i in range(A.shape[0]):
          for j in range(B.shape[1]):
            for k in range(B.shape[0]):
              T[i,j] += A[i,k] * B[k,j]
      elif len(A.shape) == 3:
        for b in range(A.shape[0]):
          for i in range(A.shape[1]):
            for j in range(B.shape[1]):
              for k in range(B.shape[0]):
                T[b,i,j] += A[b,i,k] * B[k,j]
      else:
        raise ValueError("A.shape[-1] != B.shape[-2]")
    return T


C = matrixmul(A,B)
c_torch = A@B
print(torch.allclose(C, c_torch))

True


In [ ]:
# ============================================================
# 2. MATRIX MULTIPLICATION - using einsum
# ============================================================

A = torch.randn(2, 3, 4)
B = torch.randn(4, 5)
def matrixmul(A: torch.Tensor, B: torch.Tensor) -> torch.Tensor:
    if A.shape[-1] != B.shape[-2]:
        raise ValueError("A.shape[-1] != B.shape[-2]")
    else:
      if len(A.shape) == 2:
        T = torch.einsum('ij,jk->ik', A, B)
      elif len(A.shape) == 3 and len(B.shape) == 3:
        T = torch.einsum('bij,bjk->bik', A, B)
      elif len(A.shape) == 3 and len(B.shape) == 2:
        T = torch.einsum('bij,jk->bik', A, B)
      else:
        raise ValueError("A.shape[-1] != B.shape[-2]")
    return T



C = matrixmul(A,B)
c_torch = A@B
print(torch.allclose(C, c_torch))

True


In [ ]:
# ============================================================
# 2. SOFTMAX
# ============================================================
def denji_softmax(A: torch.Tensor, dim: int) -> torch.Tensor:
    if dim+1 > len(A.shape):
      raise ValueError("Index out of range")
    if dim < 0:
      dim += len(A.shape)

    x = A.transpose(dim, -1)
    original_shape = x.shape
    x = x.reshape(-1, x.shape[-1])
    output = torch.zeros_like(x)
    for row in range(x.shape[0]):
      max_val = x[row].max()
      output[row] = torch.exp(x[row] - max_val)
      output[row] = output[row] / output[row].sum()
    output = output.reshape(original_shape)
    output = output.transpose(dim, -1)
    return output






In [ ]:
A = torch.randn(3,4,5)
print(A)

tensor([[[ 0.2303,  1.8350,  0.7603,  0.0185, -1.5331],
         [ 0.3529,  0.1425, -0.2510, -0.7038, -0.3389],
         [ 0.7975,  1.4953, -0.2722,  0.8642,  1.0782],
         [ 0.7654,  1.2751, -2.0741,  0.4047,  0.5132]],

        [[ 1.3303, -0.0436,  1.5800,  1.2581,  0.5648],
         [ 1.4732, -0.7389, -1.0581, -0.1678, -0.1081],
         [ 0.7089,  1.3773, -0.7161, -0.9953,  0.4975],
         [ 0.6821, -1.1819, -1.1950,  1.2421,  1.5984]],

        [[-0.1081,  0.3529,  0.8647, -0.5461,  0.6101],
         [ 1.1894,  0.4277,  1.3616, -0.4366, -1.3191],
         [ 0.6343,  0.6138,  0.5648, -0.5578,  1.1959],
         [ 0.4599, -1.4386,  2.2158,  0.8465, -0.1521]]])


In [ ]:
denji_softmax(A, 1)

tensor([[[0.1785, 0.4053, 0.5622, 0.1892, 0.0390],
         [0.2018, 0.0746, 0.2045, 0.0919, 0.1287],
         [0.3148, 0.2886, 0.2002, 0.4407, 0.5307],
         [0.3049, 0.2315, 0.0330, 0.2783, 0.3016]],

        [[0.3112, 0.1678, 0.8101, 0.4293, 0.1902],
         [0.3590, 0.0837, 0.0579, 0.1032, 0.0971],
         [0.1672, 0.6948, 0.0815, 0.0451, 0.1779],
         [0.1627, 0.0538, 0.0505, 0.4225, 0.5348]],

        [[0.1173, 0.2823, 0.1380, 0.1403, 0.2934],
         [0.4293, 0.3042, 0.2268, 0.1565, 0.0426],
         [0.2464, 0.3664, 0.1022, 0.1386, 0.5271],
         [0.2070, 0.0471, 0.5329, 0.5646, 0.1369]]])

In [ ]:
A

tensor([[[ 0.2334,  0.4323, -1.1853, -0.0397],
         [-0.0378,  0.8857, -0.2540,  2.9815],
         [-1.5788, -0.0843,  1.0746,  1.2718],
         [-0.7391, -0.8849,  0.6920, -0.5701],
         [-0.0289, -0.4520,  0.1799,  1.3843]],

        [[-0.5982, -0.1895,  0.8248,  1.1799],
         [-0.4640,  0.1205, -0.0184,  1.0706],
         [-0.3460, -1.6640,  0.1561,  1.5048],
         [ 0.3971, -0.9844,  1.1633,  0.0735],
         [ 0.5800, -1.3019, -0.4131, -1.0293]],

        [[ 0.3527, -0.7751,  0.9735,  2.2150],
         [-0.4223, -0.0059,  1.5322,  1.8284],
         [-0.1271,  1.0338, -0.0882,  0.3153],
         [-0.9859, -0.6337, -0.1280,  1.4365],
         [ 1.1829,  0.3541, -1.5915,  1.1172]]])

In [ ]:
A = A.reshape(-1, A.shape[-1])

In [ ]:
for row in range(A.shape[0]):
  print(A[row])

tensor([ 0.2334,  0.4323, -1.1853, -0.0397])
tensor([-0.0378,  0.8857, -0.2540,  2.9815])
tensor([-1.5788, -0.0843,  1.0746,  1.2718])
tensor([-0.7391, -0.8849,  0.6920, -0.5701])
tensor([-0.0289, -0.4520,  0.1799,  1.3843])
tensor([-0.5982, -0.1895,  0.8248,  1.1799])
tensor([-0.4640,  0.1205, -0.0184,  1.0706])
tensor([-0.3460, -1.6640,  0.1561,  1.5048])
tensor([ 0.3971, -0.9844,  1.1633,  0.0735])
tensor([ 0.5800, -1.3019, -0.4131, -1.0293])
tensor([ 0.3527, -0.7751,  0.9735,  2.2150])
tensor([-0.4223, -0.0059,  1.5322,  1.8284])
tensor([-0.1271,  1.0338, -0.0882,  0.3153])
tensor([-0.9859, -0.6337, -0.1280,  1.4365])
tensor([ 1.1829,  0.3541, -1.5915,  1.1172])
